name: safe_pass_app
description: Small example app to safe passwords.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.0.1
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_secure_storage: ^4.2.1
  uuid: ^3.0.5

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
